version: "3.9"
services:
  flask:
    build: .
    image: celery-practice:${TAG}
  dind:
    build: ./dind
    image: dind-practice:${TAG}
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"